#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'enceladus:~/db-prices-rest/'

ssh enceladus "\
cd ~/db-prices-rest
npm i
npm update
forever stop db-prices-rest
forever start -a --uid db-prices-rest index.js"
